name: macOS Build & Release

on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show tree
        run: |
          pwd
          ls -la
          echo "---- docs ----"; ls -la docs || true
          echo "---- assets ----"; ls -la assets || true

      - name: Install deps
        env:
          HOMEBREW_NO_AUTO_UPDATE: "1"
          HOMEBREW_NO_INSTALL_CLEANUP: "1"
        run: |
          python -m pip install --upgrade pip
          test -f docs/requirements.txt || (echo "Missing docs/requirements.txt"; exit 1)
          python -m pip install -r docs/requirements.txt
          python -m pip install pyinstaller
          brew install create-dmg

      - name: Build .app (PyInstaller)
        run: |
          ICON_FLAG=""
          if [ -f assets/stegocrypt.icns ]; then ICON_FLAG="--icon assets/stegocrypt.icns"; fi
          pyinstaller --clean --windowed --name "StegoCrypt" ${ICON_FLAG} --collect-submodules=cv2 --collect-submodules=Crypto --collect-all=PIL main.py
          ls -la dist || true

      - name: Create DMG
        run: |
          test -d "dist/StegoCrypt.app" || (echo "No .app found"; exit 1)
          create-dmg --volname "StegoCrypt" --window-pos 200 120 --window-size 600 400 --icon-size 100 --app-drop-link 425 120 "dist/StegoCrypt-Setup.dmg" "dist/StegoCrypt.app"
          ls -la dist || true

      - name: Upload to Release (DMG)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/StegoCrypt-Setup.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-artifacts
          path: |
            dist/**
            build/**
            *.spec
          if-no-files-found: warn
