name: macOS Build & Release

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install deps
        env:
          HOMEBREW_NO_AUTO_UPDATE: "1"
          HOMEBREW_NO_INSTALL_CLEANUP: "1"
        run: |
          python -m pip install --upgrade pip
          test -f docs/requirements.txt || (echo "Missing docs/requirements.txt"; exit 1)
          python -m pip install -r docs/requirements.txt
          python -m pip install pyinstaller
          brew install create-dmg

      - name: Build .app (PyInstaller)
        run: |
          ICON_FLAG=""
          if [ -f assets/stegocrypt.icns ]; then ICON_FLAG="--icon assets/stegocrypt.icns"; fi

          ls -la dist || true

      - name: Create DMG
        run: |
          test -d "dist/StegoCrypt.app" || (echo "No .app found"; exit 1)

        uses: softprops/action-gh-release@v2
        with:
          files: dist/StegoCrypt-Setup.dmg
        env:

