name: macOS Build & Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install pyinstaller pillow
          brew install create-dmg

      - name: Ensure .icns exists (auto-generate if missing)
        run: |
          if [ ! -f assets/stegocrypt.icns ]; then
            python - <<'PY'
from PIL import Image
import os
src_candidates = ["assets/stegocrypt.png", "assets/icon.png"]
src = next((p for p in src_candidates if os.path.isfile(p)), None)
if not src:
    raise SystemExit("No PNG icon found (assets/stegocrypt.png or assets/icon.png). Add one or commit assets/stegocrypt.icns.")
im = Image.open(src).convert("RGBA")
os.makedirs("assets", exist_ok=True)
im.save("assets/stegocrypt.icns")
print("Wrote assets/stegocrypt.icns")
PY
          fi
          ls -la assets

      - name: Build .app (PyInstaller)
        run: |
          pyinstaller --windowed --name "StegoCrypt" --icon assets/stegocrypt.icns main.py
          ls -la dist

      - name: Create DMG
        run: |
          create-dmg \
            --volname "StegoCrypt" \
            --window-pos 200 120 --window-size 600 400 \
            --icon-size 100 --app-drop-link 425 120 \
            "dist/StegoCrypt-Setup.dmg" "dist/StegoCrypt.app"
          ls -la dist

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/StegoCrypt-Setup.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
