name: Linux Build & Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag to upload asset to (e.g., v1.0.2). Leave empty to skip upload.'
        required: false
        default: ''
  push:
    tags: ['v*.*.*']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0

      - name: Install pip deps
        run: |
          python -m pip install --upgrade pip
          test -f docs/requirements.txt || (echo "Missing docs/requirements.txt"; exit 1)
          python -m pip install -r docs/requirements.txt
          python -m pip install pyinstaller

      - name: Build (PyInstaller one-dir)
        run: |
          python -m PyInstaller --clean --noconfirm --windowed --name StegoCrypt \
            --collect-submodules=cv2 --collect-submodules=Crypto --collect-all=PIL \
            main.py
          ls -la dist/StegoCrypt

      - name: Package tarball
        run: |
          tar -C dist -czf StegoCrypt-linux.tar.gz StegoCrypt
          ls -la StegoCrypt-linux.tar.gz

      # Upload to the current run's artifacts (always available for manual download)
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifacts
          path: |
            StegoCrypt-linux.tar.gz
            dist/**
            build/**
            *.spec
          if-no-files-found: warn

      # Upload to GitHub Release when run manually with an input tag
      - name: Upload to Release (manual with input tag)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.release_tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release_tag }}
          files: StegoCrypt-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload to GitHub Release when triggered by a tag push
      - name: Upload to Release (tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: StegoCrypt-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
