name: Linux Build & Release (AppImage)

on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show tree
        run: |
          pwd
          ls -la
          echo "---- docs ----"; ls -la docs || true
          echo "---- assets ----"; ls -la assets || true

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0 zsync

      - name: Install pip deps
        run: |
          python -m pip install --upgrade pip
          test -f docs/requirements.txt || (echo "Missing docs/requirements.txt"; exit 1)
          python -m pip install -r docs/requirements.txt
          python -m pip install pyinstaller appimage-builder

      - name: Build (PyInstaller one-dir)
        run: |
          pyinstaller --clean --noconfirm --windowed --name "StegoCrypt" --collect-submodules=cv2 --collect-submodules=Crypto --collect-all=PIL main.py
          ls -la dist/StegoCrypt

      - name: Create AppDir structure
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          cp -r dist/StegoCrypt/* AppDir/usr/bin/
          printf "[Desktop Entry]\nName=StegoCrypt\nExec=StegoCrypt\nIcon=stegocrypt\nType=Application\nCategories=Utility;\n" > AppDir/usr/share/applications/stegocrypt.desktop
          if [ -f assets/stegocrypt.png ]; then
            cp assets/stegocrypt.png AppDir/usr/share/icons/hicolor/256x256/apps/stegocrypt.png
          else
            python -c "from PIL import Image,ImageDraw; import os; os.makedirs('AppDir/usr/share/icons/hicolor/256x256/apps',exist_ok=True); im=Image.new('RGBA',(256,256),(30,30,36,255)); d=ImageDraw.Draw(im); d.rectangle((48,64,208,208), fill=(0,120,215,255)); im.save('AppDir/usr/share/icons/hicolor/256x256/apps/stegocrypt.png')"
          fi
          printf "version: 1\nAppDir:\n  path: ./AppDir\n  app_info:\n    id: stegocrypt\n    name: StegoCrypt\n    icon: stegocrypt\n    exec: usr/bin/StegoCrypt\n    version: 1.0.0\n  runtime:\n    env:\n      APPDIR_LIBRARY_PATH: \$APPDIR/usr/lib:\$APPDIR/usr/lib/x86_64-linux-gnu\nAppImage:\n  arch: x86_64\n" > AppImageBuilder.yml
          cat AppImageBuilder.yml

      - name: Build AppImage
        run: |
          appimage-builder --recipe AppImageBuilder.yml --skip-tests
          ls -la *.AppImage

      - name: Upload to Release (AppImage)
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifacts
          path: |
            dist/**
            build/**
            *.spec
            *.AppImage
          if-no-files-found: warn
