name: macOS Build & Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install pyinstaller pillow
          brew install create-dmg

      - name: Prepare icon (.icns) or skip
        id: icon
        run: |
          set -e
          ICON_FLAG=""
          if [ -f assets/stegocrypt.icns ]; then
            echo "ICNS exists."
            ICON_FLAG="--icon assets/stegocrypt.icns"
          elif [ -f assets/stegocrypt.png ] || [ -f assets/icon.png ]; then
            python - <<'PY'
from PIL import Image, UnidentifiedImageError
import os
src = "assets/stegocrypt.png" if os.path.isfile("assets/stegocrypt.png") else "assets/icon.png"
try:
    im = Image.open(src).convert("RGBA")
    im.save("assets/stegocrypt.icns")
    print("Wrote assets/stegocrypt.icns")
except UnidentifiedImageError as e:
    raise SystemExit(f"Icon conversion failed: {e}")
PY
            ICON_FLAG="--icon assets/stegocrypt.icns"
          elif [ -f assets/stegocrypt.ico ]; then
            python - <<'PY'
from PIL import Image
im = Image.open("assets/stegocrypt.ico")
im.save("assets/stegocrypt.icns")
print("Converted ICO -> ICNS")
PY
            ICON_FLAG="--icon assets/stegocrypt.icns"
          else
            echo "No icon found; building without --icon"
          fi
          echo "icon_flag=$ICON_FLAG" >> $GITHUB_OUTPUT

      - name: Build .app (PyInstaller)
        run: |
          pyinstaller --windowed --name "StegoCrypt" ${{ steps.icon.outputs.icon_flag }} main.py
          ls -la dist

      - name: Create DMG
        run: |
          create-dmg \
            --volname "StegoCrypt" \
            --window-pos 200 120 --window-size 600 400 \
            --icon-size 100 --app-drop-link 425 120 \
            "dist/StegoCrypt-Setup.dmg" "dist/StegoCrypt.app"
          ls -la dist

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/StegoCrypt-Setup.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
