name: Windows Build & Release

on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show tree
        shell: powershell

      - name: Build EXE (PyInstaller)
        shell: powershell
        run: |
          $args = @(
            '-m','PyInstaller',
            '--clean','--noconfirm','--windowed',
            '--name','StegoCrypt',
            '--collect-submodules=cv2',
            '--collect-submodules=Crypto',
            '--collect-all=PIL'
          )

          if (Test-Path 'assets\stegocrypt.ico') {
            $args += @('--icon','assets\stegocrypt.ico')
          }

          $args += @('main.py')

          # Invoke: python -m PyInstaller <args...>
          & python $args
          if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed with exit code $LASTEXITCODE" }

          Get-ChildItem dist\StegoCrypt -Force




      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup --yes

      - name: Build installer (Inno Setup)
        shell: powershell
        run: |
          if (!(Test-Path installer\StegoCrypt.iss)) { throw "Missing installer\StegoCrypt.iss" }
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\StegoCrypt.iss
          Get-ChildItem installer\Output -Force

      - name: Upload to Release (EXE)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: installer/Output/StegoCrypt-Setup-*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts
          path: |
            dist/**
            build/**
            *.spec
            installer/Output/**
          if-no-files-found: warn
